### ISSUE TITLE
Server Side Crash - Exception in server tick loop on startup

### ISSUE THREAD

**Issue by JoelZBub** [iLexiconn/JurassiCraft#1]
Server OS : Ubuntu 16.04
java version :  1.8.0_72 64-bit
Forge version :  1.8.9-11.15.1.1902
llibrary version : 1.5.1-1.8.9
JurassiCraft version : 2.0.0 Pre-release 5 (obtained with Curse launcher)

Server crashes on heavily modded server with the following crash report:

[crash-2016-07-31_11.26.27-server.txt](https://github.com/iLexiconn/JurassiCraft/files/392502/crash-2016-07-31_11.26.27-server.txt)

Attempting to start a server with only llibrary and JurassiCraft as the only installed mods crashes the server with the following crash report:

[crash-2016-07-31_12.03.14-server.txt](https://github.com/iLexiconn/JurassiCraft/files/392503/crash-2016-07-31_12.03.14-server.txt)

**Comment by Gegy** [comment]
We no longer support the pre-releases.

**Comment by JoelZBub** [comment]
Will you be uploading a newer version to Curse, then so that it can be distributed easily?
Or has support for the 1.8.9 version been abandoned?

**Comment by Gegy** [comment]
The full 2.0 version is for 1.9.4 and 1.10.2 only.

**Comment by JoelZBub** [comment]
Okay, thanks. Marking as closed.
