### ISSUE TITLE
Carnivores don't hunt herbivores unless attacked by one

### ISSUE THREAD

**Issue by Kash-117** [iLexiconn/JurassiCraft#163]

**Comment by KingRaptorius** [comment]
Tyrannosaurus Rex hunts them, Carno, Herrera, And Velociraptors don't.

**Comment by PCAwesomeness** [comment]
@KingRaptorius 

Herrerasaurus and Velociraptor hunt Hypsilophodon fine. However, Tyrannosaurus rex only hunts Gallimimus, Herrerasaurus and Velociraptor only hunt Hypsilophodon, and Carnotaurus doesn't hunt anything at all.

**Comment by PCAwesomeness** [comment]
Actually, all current carnivores now hunt Hypsilophodon fine, and Tyrannosaurus rex hunts Gallimimus fine.
