### ISSUE TITLE
Theropod speeds

### ISSUE THREAD

**Issue by PCAwesomeness** [iLexiconn/JurassiCraft#179]
Since the Tyrannosaurus speed is pretty accurate, I have some suggestions for the mod.

Dilophosaurus and Velociraptor should run at approximately 8.7 and 8.9 bps respectively.}

Gallimimus should run at 9.5 bps.

I hope someone could look upon this!

**Comment by BobMowzie** [comment]
Yeah, all of the dinosaur stats need rebalancing...
