### ISSUE TITLE
Mob sounds

### ISSUE THREAD

**Issue by PCAwesomeness** [iLexiconn/JurassiCraft#180]
Well, most of the sounds are now in, so good job. But none of the sounds for the reptile-class mobs are working, and Parasaurolophus, Velociraptor, Tyrannosaurus rex, Titanis, Leptictidium, Arsinoitherium, and the wooly mammoth need some sounds as well.

**Comment by Rydog101** [comment]
There are still sounds in the process of getting labelled right to be used

**Comment by PCAwesomeness** [comment]
OK, Rex now has sounds. Now we just need Velociraptor and Parasaurolophus.

**Comment by Rydog101** [comment]
Once there labelled correctly they will be added

**Comment by PCAwesomeness** [comment]
Tyrannosaurus, Leptictidium, and the wooly mammoth are done! Now we just need Titanis, Arsinoitherium, Velociraptor, and Parasaurolophus sounds!

**Comment by Rydog101** [comment]
Do they work or are they just in I haven't test it yet

**Comment by PCAwesomeness** [comment]
They are just in.

**Comment by Rydog101** [comment]
OK I'll get them working a bit later on today
I'm busy atm

**Comment by PCAwesomeness** [comment]
Well, they might be working. I dunno.

**Comment by PCAwesomeness** [comment]
Welp, these sounds still don't work.

**Comment by PCAwesomeness** [comment]
And all the sounds don't work anymore.

**Comment by PCAwesomeness** [comment]
The T.rex roar noise isn't working.
