### ISSUE TITLE
Using TooManyItems with the mod crashes the game whenever E is clicked

### ISSUE THREAD

**Issue by Kash-117** [iLexiconn/JurassiCraft#191]

**Comment by PCAwesomeness** [comment]
Why don't they use Not Enough Items instead? It's better.

**Comment by jochuan** [comment]
no not enough items makes my game stop responding when i go to the second page

**Comment by Rydog101** [comment]
can we have logs

**Comment by Kash-117** [comment]
Jochuan we can't keep trying to make the mod compatible with a machine that clearly can't handle having many mods installed on it. You need to find ways to maximize minecraft's performance

**Comment by BobMowzie** [comment]
This has nothing to do with Jochuan's hardware. We have an incompatibility with Too Many Items.

**Comment by PCAwesomeness** [comment]
@BobMowzie 

Yeah. As I said, Not Enough Items is waaaaaaaay better, as it's more aesthetically pleasing, and it could give you crafting recipes.

Close this, please.

**Comment by BobMowzie** [comment]
No. No doubt the same incompatibility will apply to some other mods.

**Comment by mineme45** [comment]
Can we have logs (Stacktrace) for this crash?

**Comment by iLexiconn** [comment]
Works fine with NEI
