### ISSUE TITLE
DNA regression

### ISSUE THREAD

**Issue by mineme45** [iLexiconn/JurassiCraft#198]
There is a regression between build-119 and build-132.
Logs are available here:
http://pastebin.com/CMNDHWce

Now all DNA loose is name ingame: http://img15.hostingpics.net/pics/76802520150331224352.png

Thanks

**Comment by mineme45** [comment]
I've look at the code, I think it's come with #153
There is now a toLowerCase() on the name, but the .lang file need an update too?

item.Stegosaurus_DNA.name=Stegosaurus DNA -> item.stegosaurus_DNA.name

**Comment by Rydog101** [comment]
This will be fixed soon
Still working on cleaning up assets
