### ISSUE TITLE
spawn eggs are wrong

### ISSUE THREAD

**Issue by jochuan** [iLexiconn/JurassiCraft#200]
the spawn eggs are spawning wrong dinosaurs, when i used one spawn egg for oviraptor it spawned one gallimimus

**Comment by Kash-117** [comment]
jochuan you're bugs are not relevant to anyone, oviraptor has been disabled for quite some time now. You seem to get the most unique, random, probably BS, and weirdest bugs that no one else on the forums and team gets. If you want to continue to play minecraft with mods, get a new computer and then tell us if you experience the same bugs
