### ISSUE TITLE
the brazil translation is wrong

### ISSUE THREAD

**Issue by jochuan** [iLexiconn/JurassiCraft#203]
the portuguese translation for the spawn eggs are wrong, the egg for velociraptor in portuguese is saying that the egg is a braquiossaur egg and kash this  isnt my computer fault and other eggs have the translation wrong too

**Comment by jochuan** [comment]
https://github.com/iLexiconn/JurassiCraft/issues/200

**Comment by Kash-117** [comment]
Lol don't worry the translations and Lang files are a bit screwed up atm. We're on it :)  and sorry for yelling at you before
