### ISSUE TITLE
Carnotaurus, Trex and maybe more can't spawn

### ISSUE THREAD

**Issue by CalZe** [iLexiconn/JurassiCraft#206]
I've tried the spawn in egg, baby and adult in creative, nothing, I've tried them made legit, it just goes way over the 100% mark, any help with this?

**Comment by Kash-117** [comment]
Did you check the quality of the egg? The black spawn eggs work fine, but normal eggs with the sprites need to be 50 or higher in quality

**Comment by CalZe** [comment]
the black spawn eggs didn't work for me with them though? The egg's were fine quality, the black eggs wouldn't even work
