### ISSUE TITLE
Damage Indicators and Jurassicaft reacting weird

### ISSUE THREAD

**Issue by baluka44** [iLexiconn/JurassiCraft#213]
For whatever reason when I have damage indicators installed, It causes all aquatic mobs (besides the Basilosaur) to do a continually looping spin, and all the tails of land dinos to curl up on itself and twitch. 

Here is a picture example of both:
http://oi59.tinypic.com/2pqj67s.jpg
http://oi61.tinypic.com/98suaq.jpg

**Comment by iLexiconn** [comment]
Sorry, but we can't do anything about this. Damage Indicators doesn't understand the rotations and animations our models have.
