### ISSUE TITLE
Animation associated sounds are still broken

### ISSUE THREAD

**Issue by BobMowzie** [iLexiconn/JurassiCraft#226]
I can't run the project, so I don't know which ones, but check the following:
Trex growl, roar, and step
Parasaurolophus trumpet
Triceratops charge
Velociraptor everything (including leap sounds)

The sounds are played in the entity file or in the respective animation AI file. Please fix these.

**Comment by BobMowzie** [comment]
Still missing:
Triceratops charge
Velociraptor everything (including leap sounds)

**Comment by iLexiconn** [comment]
Will close this, look at #233 instead.
